Add dockerfile
chrieke/prettymapp pull request #46
Opened 2024-01-31 14:30 UTC by chrieke

As intended in https://github.com/chrieke/prettymapp/pull/42 adds Dockerfile & readme instrunctions.

But keeps the same code folder structure.

2024-02-04 19:35 UTC, Saibamen requested changes
Added cleanup suggestions to reduce final docker image size, based on https://github.com/google-deepmind/alphafold/ repo

2024-02-04 19:35 UTC, Saibamen commented on Dockerfile
> +RUN apt-get update && apt-get install -y \
```suggestion
RUN apt-get update && apt-get install --no-install-recommends -y \
```

2024-02-04 19:35 UTC, Saibamen commented on Dockerfile
> +    && rm -rf /var/lib/apt/lists/*
```suggestion
    && rm -rf /var/lib/apt/lists/* \
    && apt-get autoremove -y \
    && apt-get clean
```

2024-02-04 19:35 UTC, Saibamen commented on Dockerfile
> +RUN mkdir -p /app/streamlit-prettymapp
This is not needed - will be created during `COPY` command

2024-02-04 19:35 UTC, Saibamen commented on Dockerfile
> +RUN pip3 install -r streamlit-prettymapp/requirements.txt
```suggestion
RUN pip3 install --upgrade pip --no-cache-dir \
    && pip3 install -r streamlit-prettymapp/requirements.txt --no-cache-dir
```

2024-02-04 19:35 UTC, Saibamen commented on README.md
> +
Remove double empty lines

2024-02-04 19:35 UTC, Saibamen commented on README.md
> +```bash
Fix markdownlint
```suggestion
see the streamlit app.

```bash
```

2024-02-04 19:35 UTC, Saibamen commented on Dockerfile
> +FROM python:3.11-slim
Use latest 3.12 if is possible

2024-02-05 18:02 UTC, chrieke commented
Thank you @Saibamen!

2024-02-05 20:14 UTC, Saibamen commented
>pushes it down to 1.57GB

How much it was before?

2024-02-05 20:16 UTC, Saibamen requested changes

2024-02-05 20:16 UTC, Saibamen commented on README.md
> +
Not resolved

2024-02-05 20:16 UTC, Saibamen commented on Dockerfile
> +FROM python:3.11-slim
@chrieke ?

2024-02-05 20:16 UTC, Saibamen commented on README.md
> +```bash
Not resolved
@chrieke https://github.com/DavidAnson/markdownlint

2024-02-05 20:16 UTC, Saibamen commented on Dockerfile
> +RUN mkdir -p /app/streamlit-prettymapp
Did you test it @chrieke?

2024-04-20 17:10 UTC, chrieke commented
Closing, Dockerfile added in https://github.com/chrieke/prettymapp/pull/42

2024-04-20 17:10 UTC, closed without merging